In [1]:
import pandas as pd
import numpy as np
cr = pd.read_csv("quikr_car.csv")
cr

name    company  year          Price  \
0      Hyundai Santro Xing XO eRLX Euro III    Hyundai  2007         80,000   
1                   Mahindra Jeep CL550 MDI   Mahindra  2006       4,25,000   
2                Maruti Suzuki Alto 800 Vxi     Maruti  2018  Ask For Price   
3    Hyundai Grand i10 Magna 1.2 Kappa VTVT    Hyundai  2014       3,25,000   
4          Ford EcoSport Titanium 1.5L TDCi       Ford  2014       5,75,000   
..                                      ...        ...   ...            ...   
891               Chevrolet Sail 1.2 LT ABS  Chevrolet  2014       1,60,000   
892             Mahindra Scorpio VLX Airbag  Mahindra   2012       5,00,000   
893                      Mahindra XUV500 W8   Mahindra  2015       8,42,000   
894       Maruti Suzuki Swift Dzire VDI ABS     Maruti  2015       5,94,000   
895       MG Motors Hector 1.5 Hybrid Sharp         MG  2020      16,65,000   

     kms_driven fuel_type  
0    45,000 kms    Petrol  
1        40 kms    Diesel  
2    22,000 kms    Petrol  
3    28,000 kms    Petrol  
4    36,000 kms    Diesel  
..          ...       ...  
891      Petrol       NaN  
892   55,000kms    Petrol  
893    113.5kms    Diesel  
894    109.7kms    Diesel  
895     20.2kms    Petrol  

[896 rows x 6 columns]

In [2]:
cr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 896 entries, 0 to 895
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        896 non-null    object
 1   company     896 non-null    object
 2   year        896 non-null    object
 3   Price       896 non-null    object
 4   kms_driven  844 non-null    object
 5   fuel_type   841 non-null    object
dtypes: object(6)
memory usage: 42.1+ KB


In [3]:
cr['year'].unique()

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest', '2020'], dtype=object)

In [4]:
cr['Price'].unique()

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,5

In [5]:
cr['kms_driven'].unique()

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,

In [6]:
cr['fuel_type'].unique()

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [7]:
backup=cr.copy()

In [8]:
cr=cr[cr['year'].str.isnumeric()]

In [9]:
cr['year']=cr['year'].astype(int)

C:\Users\BHAGAVATHI\AppData\Local\Temp\ipykernel_15736\1662567518.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cr['year']=cr['year'].astype(int)


In [10]:
cr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 846 entries, 0 to 895
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        846 non-null    object
 1   company     846 non-null    object
 2   year        846 non-null    int32 
 3   Price       846 non-null    object
 4   kms_driven  844 non-null    object
 5   fuel_type   841 non-null    object
dtypes: int32(1), object(5)
memory usage: 43.0+ KB


In [11]:
cr=cr[cr['Price']!="Ask For Price"]

In [12]:
cr['Price']=cr['Price'].str.replace(',','').astype(int)

In [13]:
cr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 823 entries, 0 to 895
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        823 non-null    object
 1   company     823 non-null    object
 2   year        823 non-null    int32 
 3   Price       823 non-null    int32 
 4   kms_driven  823 non-null    object
 5   fuel_type   820 non-null    object
dtypes: int32(2), object(4)
memory usage: 38.6+ KB


In [14]:
cr['kms_driven']=cr['kms_driven'].str.split(' ').str.get(0).str.replace(',','')

In [15]:
cr=cr[cr['kms_driven'].str.isnumeric()]

In [16]:
cr['kms_driven']=cr['kms_driven'].astype(int)

In [17]:
cr.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 817 entries, 0 to 889
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        817 non-null    object
 1   company     817 non-null    object
 2   year        817 non-null    int32 
 3   Price       817 non-null    int32 
 4   kms_driven  817 non-null    int32 
 5   fuel_type   816 non-null    object
dtypes: int32(3), object(3)
memory usage: 35.1+ KB


In [18]:
cr=cr[~cr['fuel_type'].isna()]

In [19]:
cr=cr.reset_index(drop=True)

In [20]:
cr

name   company  year   Price  \
0      Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007   80000   
1                   Mahindra Jeep CL550 MDI  Mahindra  2006  425000   
2    Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014  325000   
3          Ford EcoSport Titanium 1.5L TDCi      Ford  2014  575000   
4                                 Ford Figo      Ford  2012  175000   
..                                      ...       ...   ...     ...   
811              Maruti Suzuki Ritz VXI ABS    Maruti  2011  270000   
812               Tata Indica V2 DLE BS III      Tata  2009  110000   
813                    Toyota Corolla Altis    Toyota  2009  300000   
814                     Tata Zest XM Diesel      Tata  2018  260000   
815                      Mahindra Quanto C8  Mahindra  2013  390000   

     kms_driven fuel_type  
0         45000    Petrol  
1            40    Diesel  
2         28000    Petrol  
3         36000    Diesel  
4         41000    Diesel  
..          ...       ...  
811       50000    Petrol  
812       30000    Diesel  
813      132000    Petrol  
814       27000    Diesel  
815       40000    Diesel  

[816 rows x 6 columns]

In [21]:
cr.describe()

year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [22]:
cr.to_csv('cleaned data2.csv')

In [23]:
x=cr.drop(columns='Price')
y=cr['Price']

In [24]:
x

name   company  year  kms_driven  \
0      Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007       45000   
1                   Mahindra Jeep CL550 MDI  Mahindra  2006          40   
2    Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014       28000   
3          Ford EcoSport Titanium 1.5L TDCi      Ford  2014       36000   
4                                 Ford Figo      Ford  2012       41000   
..                                      ...       ...   ...         ...   
811              Maruti Suzuki Ritz VXI ABS    Maruti  2011       50000   
812               Tata Indica V2 DLE BS III      Tata  2009       30000   
813                    Toyota Corolla Altis    Toyota  2009      132000   
814                     Tata Zest XM Diesel      Tata  2018       27000   
815                      Mahindra Quanto C8  Mahindra  2013       40000   

    fuel_type  
0      Petrol  
1      Diesel  
2      Petrol  
3      Diesel  
4      Diesel  
..        ...  
811    Petrol  
812    Diesel  
813    Petrol  
814    Diesel  
815    Diesel  

[816 rows x 5 columns]

In [25]:
y

0       80000
1      425000
2      325000
3      575000
4      175000
        ...  
811    270000
812    110000
813    300000
814    260000
815    390000
Name: Price, Length: 816, dtype: int32

In [26]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5)

In [27]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [28]:
ohe = OneHotEncoder()
ohe.fit(x[['name','company','fuel_type']])

OneHotEncoder()

In [29]:
ohe.categories_

[array(['Audi A3 Cabriolet 40 TFSI',
        'Audi A4 1.8 TFSI Multitronic Premium Plus',
        'Audi A4 2.0 TDI 177bhp Premium', 'Audi A6 2.0 TDI Premium',
        'Audi A8', 'Audi Q3 2.0 TDI quattro Premium',
        'Audi Q5 2.0 TDI quattro Premium Plus', 'Audi Q7',
        'BMW 3 Series 320d Sedan', 'BMW 3 Series 320i',
        'BMW 5 Series 520d Sedan', 'BMW 5 Series 530i',
        'BMW 7 Series 740Li Sedan', 'BMW X1', 'BMW X1 sDrive20d',
        'BMW X1 xDrive20d xLine', 'Chevrolet Beat',
        'Chevrolet Beat Diesel', 'Chevrolet Beat LS Diesel',
        'Chevrolet Beat LS Petrol', 'Chevrolet Beat LT Diesel',
        'Chevrolet Beat LT Opt Diesel', 'Chevrolet Beat LT Petrol',
        'Chevrolet Beat PS Diesel', 'Chevrolet Cruze LTZ',
        'Chevrolet Cruze LTZ AT', 'Chevrolet Enjoy',
        'Chevrolet Enjoy 1.4 LS 8 STR', 'Chevrolet Sail 1.2 LS',
        'Chevrolet Sail UVA Petrol LT ABS', 'Chevrolet Spark',
        'Chevrolet Spark 1.0 LT', 'Chevrolet Spark LS 1.0',
     

In [30]:
column_trans = make_column_transformer((OneHotEncoder(categories=ohe.categories_),['name','company','fuel_type']),remainder='passthrough')

In [31]:
lr=LinearRegression()

In [32]:
pipe=make_pipeline(column_trans,lr)

In [33]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet 40 TFSI',
       'Audi A4 1.8 TFSI Multitronic Premium Plus',
       'Audi A4 2.0 TDI 177bhp Premium', 'Audi A6 2.0 TDI Premium',
       'Audi A8', 'Audi Q3 2.0 TDI quattro Premium',
       'Audi Q5 2.0 TDI quattro Premium Plus', 'Audi Q7',
       'BMW 3 Series 320d...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [34]:
y_pred=pipe.predict(x_test)

In [35]:
r2_score(y_test,y_pred)

0.435725524079006

In [36]:
scores=[]
for i in range(1000):
    x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=i)
    lr=LinearRegression()
    pipe=make_pipeline(column_trans,lr)
    pipe.fit(x_train,y_train)
    y_pred=pipe.predict(x_test)
    scores.append(r2_score(y_test,y_pred))

In [37]:
np.argmax(scores)

572

In [38]:
scores[np.argmax(scores)]

0.6906557782781759

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=np.argmax(scores))
lr=LinearRegression()
pipe=make_pipeline(column_trans,lr)
pipe.fit(x_train,y_train)
y_pred=pipe.predict(x_test)
r2_score(y_test,y_pred)

0.6906557782781759

In [40]:
import pickle
pickle.dump(pipe,open('LinearRegressionModel.pkl','wb'))

In [41]:
pipe.predict(pd.DataFrame([['Honda Amaze','Honda',2015,70000,'Petrol']], columns=['name','company','year','kms_driven','fuel_type']))

array([218798.01340058])

In [42]:
pipe.predict(pd.DataFrame([['Ford Figo','Ford',2018,10000,'Petrol']], columns=['name','company','year','kms_driven','fuel_type']))

array([340008.59868692])

In [43]:
pipe.predict(pd.DataFrame([['Mahindra XUV500 W8','Mahindra',2016,112,'Diesel']], columns=['name','company','year','kms_driven','fuel_type']))

array([809284.14992847])